//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class easypharmadbEntities : DbContext
    {
        public easypharmadbEntities()
            : base("name=easypharmadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Laboratories> Laboratories { get; set; }
        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<PBMProgramMedicines> PBMProgramMedicines { get; set; }
        public virtual DbSet<PBMPrograms> PBMPrograms { get; set; }
        public virtual DbSet<PBMs> PBMs { get; set; }
        public virtual DbSet<States> States { get; set; }
        public virtual DbSet<TaxByStates> TaxByStates { get; set; }
        public virtual DbSet<TherapeuticClasses> TherapeuticClasses { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
