//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicines()
        {
            this.PBMProgramMedicines = new HashSet<PBMProgramMedicines>();
        }
    
        public int Id { get; set; }
        public string EAN { get; set; }
        public string Registration { get; set; }
        public string Description { get; set; }
        public string Composition { get; set; }
        public int IdLab { get; set; }
        public int IdTherapeuticClass { get; set; }
        public int IdTaxByState { get; set; }
    
        public virtual Laboratories Laboratories { get; set; }
        public virtual TaxByStates TaxByStates { get; set; }
        public virtual TherapeuticClasses TherapeuticClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PBMProgramMedicines> PBMProgramMedicines { get; set; }
    }
}
