//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBMPrograms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PBMPrograms()
        {
            this.PBMProgramMedicines = new HashSet<PBMProgramMedicines>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdPBM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PBMProgramMedicines> PBMProgramMedicines { get; set; }
        public virtual PBMs PBMs { get; set; }
    }
}
