//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBMProgramMedicines
    {
        public int Id { get; set; }
        public double PercDescPF { get; set; }
        public double PercDescPMC { get; set; }
        public string ExtraInfo { get; set; }
        public int IdPBMProgram { get; set; }
        public int IdMedicine { get; set; }
    
        public virtual Medicines Medicines { get; set; }
        public virtual PBMPrograms PBMPrograms { get; set; }
    }
}
